# Generated by Django 5.2.1 on 2025-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_memberdirectory_customuser_aadhaar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberDirectory',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='aadhaar',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
