# Generated by Django 5.2.1 on 2025-06-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_delete_memberdirectory_alter_customuser_aadhaar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('maritalStatus', models.CharField(blank=True, max_length=20)),
                ('aadhaar', models.CharField(blank=True, max_length=12)),
                ('residentialAddress', models.TextField(blank=True)),
                ('officeAddress', models.TextField(blank=True)),
                ('postOffice', models.CharField(blank=True, max_length=100)),
                ('pin', models.CharField(blank=True, max_length=10)),
                ('licenseNo', models.CharField(blank=True, max_length=50)),
                ('licenseDate', models.DateField(blank=True, null=True)),
                ('renewalDate', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('additionalQualification', models.CharField(blank=True, max_length=200)),
                ('skills', models.CharField(blank=True, max_length=200)),
                ('bloodGroup', models.CharField(blank=True, max_length=5)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('panchayath', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
