# Generated by Django 5.2.1 on 2025-06-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_memberapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('member', 'Member'), ('both', 'Both')], default='user', max_length=10),
        ),
    ]
