# Generated by Django 5.2.1 on 2025-06-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('member', 'Member'), ('admin', 'Admin'), ('both', 'Both')], default='user', max_length=10),
        ),
    ]
