# Generated by Django 5.2.1 on 2025-06-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_customuser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
