# Generated by Django 5.2.1 on 2025-06-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_memberapplication_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
