# Generated by Django 5.2.1 on 2025-06-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_customuser_location_memberapplication_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
