# Generated by Django 5.2.1 on 2025-06-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_alter_customuser_aadhaar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='location',
        ),
    ]
