# Generated by Django 5.2.1 on 2025-06-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_remove_customuser_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('area_admin', 'Area Admin'), ('unit_admin', 'Unit Admin'), ('admin', 'Admin')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
